StoreFront.UI.MVC/StoreFront.UI.MVC/Controllers/CoffeeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StoreFront.DATA.EF;
using StoreFront.UI.MVC.Utilities;

namespace StoreFront.UI.MVC.Controllers
{
    [Authorize]
    public class CoffeeController : Controller
    {
        private StoreFrontEntities db = new StoreFrontEntities();
        #region Scaffolded, Non-Ajax CRUD Functionality

        
        // GET: Coffee
        [AllowAnonymous]
        public ActionResult Index()
        {
            ViewBag.CoffeeStatusID = new SelectList(db.CoffeeStatus, "CoffeeStatusID", "StatusName");
            ViewBag.SupplierID = new SelectList(db.CoffeeSuppliers, "SupplierID", "SupplierName");
            ViewBag.TypeID = new SelectList(db.CoffeeTypes, "TypeID", "Name");
            var coffees = db.Coffees.Include(c => c.CoffeeStatu).Include(c => c.CoffeeSupplier).Include(c => c.CoffeeType);
            return View(coffees.ToList());
        }

        // GET: Coffee/Details/5 
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Coffee coffee = db.Coffees.Find(id);
            if (coffee == null)
            {
                return HttpNotFound();
            }
            return View(coffee);
        }

        // GET: Coffee/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.CoffeeStatusID = new SelectList(db.CoffeeStatus, "CoffeeStatusID", "StatusName");
            ViewBag.SupplierID = new SelectList(db.CoffeeSuppliers, "SupplierID", "SupplierName");
            ViewBag.TypeID = new SelectList(db.CoffeeTypes, "TypeID", "Name");
            return View();
        }

        // POST: Coffee/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]    
        public ActionResult Create([Bind(Include = "CoffeeID,CoffeeName,TypeID,Price,Description,CoffeeStatusID,SupplierID,Images,Country,Region")] Coffee coffee, HttpPostedFileBase coffeeBag)
        {
            if (ModelState.IsValid)
            {
                #region File Upload w/ Utility
                string file = "NoImage.png";

                if (coffeeBag != null)
                {
                    file = coffeeBag.FileName;

                    string ext = file.Substring(file.LastIndexOf("."));

                    string[] goodExts = {".jpeg",".jpg",".gif",".png" };

                    if (goodExts.Contains(ext))
                    {
                        file = Guid.NewGuid() + ext;

                        #region Resize Image

                        //file path
                        string savePath = Server.MapPath("~/Content/images/coffeemessenger");
                        //image file
                        Image convertedImage = Image.FromStream(coffeeBag.InputStream);
                        //max img size
                        int maxImageSize = 500;

                        //max thumb size
                        int maxThumbSize = 100;

                        //call the imageutlity to do work
                        ImageUtility.ResizeImage(savePath, file, convertedImage, maxImageSize, maxThumbSize);
                        #endregion
                    }
                    else
                    {
                        file = "NoImage.png";
                    }

                    coffee.Images = file;

                }
                #endregion
               // ViewBag.TypeID = new SelectList(db.CoffeeTypes, "TypeID", "Name");
                db.Coffees.Add(coffee);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CoffeeStatusID = new SelectList(db.CoffeeStatus, "CoffeeStatusID", "StatusName", coffee.CoffeeStatusID);
            ViewBag.SupplierID = new SelectList(db.CoffeeSuppliers, "SupplierID", "SupplierName", coffee.SupplierID);
            ViewBag.TypeID = new SelectList(db.CoffeeTypes, "TypeID", "Name", coffee.TypeID);
            return View(coffee);
        }

        // GET: Coffee/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Coffee coffee = db.Coffees.Find(id);
            if (coffee == null)
            {
                return HttpNotFound();
            }
            ViewBag.CoffeeStatusID = new SelectList(db.CoffeeStatus, "CoffeeStatusID", "StatusName", coffee.CoffeeStatusID);
            ViewBag.SupplierID = new SelectList(db.CoffeeSuppliers, "SupplierID", "SupplierName", coffee.SupplierID);
            ViewBag.TypeID = new SelectList(db.CoffeeTypes, "TypeID", "Name", coffee.TypeID);
            return View(coffee);
        }

        // POST: Coffee/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]      
        public ActionResult Edit([Bind(Include = "CoffeeID,CoffeeName,TypeID,Price,Description,CoffeeStatusID,SupplierID,Images,Country,Region")] Coffee coffee, HttpPostedFileBase coffeeBag)
        {
            if (ModelState.IsValid)
            {
                #region File Upload w/ Utility               

                string file = "";

                if (coffeeBag != null)
                {
                    
                    file = coffeeBag.FileName;                  

                    string ext = file.Substring(file.LastIndexOf("."));

                    string[] goodExts = { ".jpg", ".jpeg", ".png", ".gif" };

                    if (goodExts.Contains(ext))
                    {

                        
                        file = Guid.NewGuid() + ext;

                        #region Resize Image
                        
                        string savePath = Server.MapPath("~/Content/imgstore/books/");

                        Image convertedImage = Image.FromStream(coffeeBag.InputStream);

                        int maxImageSize = 500;

                        int maxThumbSize = 100;

                        ImageUtility.ResizeImage(savePath, file, convertedImage, maxImageSize, maxThumbSize);
                        #endregion

                        #region Delete the old image
                        if (coffee.Images != null && coffee.Images != "NoImage.png")
                        {
                            string path = Server.MapPath("~/Content/imgstore/books/");
                            ImageUtility.Delete(path, coffee.Images);
                        }
                        #endregion

                        coffee.Images = file;

                    }
                }
                #endregion
                db.Entry(coffee).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CoffeeStatusID = new SelectList(db.CoffeeStatus, "CoffeeStatusID", "StatusName", coffee.CoffeeStatusID);
            ViewBag.SupplierID = new SelectList(db.CoffeeSuppliers, "SupplierID", "SupplierName", coffee.SupplierID);
            ViewBag.TypeID = new SelectList(db.CoffeeTypes, "TypeID", "Name", coffee.TypeID);
            return View(coffee);
        }

        // GET: Coffee/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Coffee coffee = db.Coffees.Find(id);
            if (coffee == null)
            {
                return HttpNotFound();
            }
            return View(coffee);
        }

        // POST: Coffee/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]    
        public ActionResult DeleteConfirmed(int id)
        {
            Coffee coffee = db.Coffees.Find(id);
            db.Coffees.Remove(coffee);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        #endregion

        // step 2 

        // Step 9
        [AcceptVerbs(HttpVerbs.Post)]
        [Authorize(Roles = "Admin")]
        public JsonResult AjaxDelete(int id)
        {
            Coffee coffee = db.Coffees.Find(id);

            db.Coffees.Remove(coffee);
            db.SaveChanges();

            string confirmMessage = $"Delete Coffee item {coffee.CoffeeName} from the database!";

            return Json(new { id = id, message = confirmMessage });
        }

        //Step 13
        [HttpGet]
        public PartialViewResult CoffeeDetails(int id)
        {
            Coffee coffee = db.Coffees.Find(id);
            return PartialView(coffee);

            //Create partial View()
        }

        //[HttpGet]
        //[Authorize(Roles = "Admin")]
        //public JsonResult AjaxCreate()
        //{
        //    ViewBag.CoffeeStatusID = new SelectList(db.CoffeeStatus, "CoffeeStatusID", "StatusName");
        //    ViewBag.SupplierID = new SelectList(db.CoffeeSuppliers, "SupplierID", "SupplierName");
        //    ViewBag.TypeID = new SelectList(db.CoffeeTypes.OrderBy(c => c.Name), "TypeID", "Name");
        //    var coffee = db.Coffees.Include(c => c.CoffeeStatu).Include(c => c.CoffeeSupplier).Include(c => c.CoffeeType);
        //    return Json(coffee);
        //}


        //Create

StoreFront.UI.MVC/StoreFront.UI.MVC/Controllers/FiltersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using StoreFront.UI.MVC.Models;
using StoreFront.DATA.EF; //access the db b/c this was created after EF

namespace StoreFront.UI.MVC.Controllers
{
    public class FiltersController : Controller
    {
        private StoreFrontEntities db = new StoreFrontEntities();

        // GET: Filters
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CoffeeQS()
        {
            var coffee = db.Coffees.Include(c => c.CoffeeStatu).Include(c => c.CoffeeSupplier).Include(c => c.CoffeeType);


            return View(coffee.ToList());
        }

        //---------------ADDED FROM CoffeeController.cs--------//


        // step 2 

        // Step 9
        //[AcceptVerbs(HttpVerbs.Post)]
        //public JsonResult AjaxDelete(int id)
        //{
        //    Coffee coffee = db.Coffees.Find(id);

        //    db.Coffees.Remove(coffee);
        //    db.SaveChanges();

        //    string confirmMessage = $"Delete Coffee item {coffee.CoffeeName} from the database!";

        //    return Json(new { id = id, message = confirmMessage });
        //}

        ////Step 13
        //[HttpGet]
        //public PartialViewResult CoffeeDetails(int id)
        //{
        //    Coffee coffee = db.Coffees.Find(id);
        //    return PartialView(coffee);

        //    //Create partial View()
        //}


        ////Create
        ////Step 18 - Create the POST action for the ajax create submission
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public JsonResult AjaxCreate(Coffee coffee)
        //{
        //    //add + save functionality
        //    db.Coffees.Add(coffee);
        //    db.SaveChanges();

        //    //return the object back to the Json view
        //    return Json(coffee);
        //}

        ////Edit
        ////Step 22 - get action that returns partial view and form
        //[HttpGet]
        //public PartialViewResult CoffeeEdit(int id)
        //{
        //    Coffee coffee = db.Coffees.Find(id);


        //    return PartialView(coffee);
        //}

        ////Step 23 - POST action that saves the changes to the coffee
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public JsonResult AjaxEdit(Coffee coffee)
        //{
        //    db.Entry(coffee).State = EntityState.Modified;
        //    db.SaveChanges();
        //    return Json(coffee);
        //}


        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}

    }
}

StoreFront.UI.MVC/StoreFront.UI.MVC/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StoreFront.DATA.EF;
using StoreFront.UI.MVC.Models;

namespace StoreFront.UI.MVC.Controllers
{
    public class ShoppingCartController : Controller
    {
        private StoreFrontEntities db = new StoreFrontEntities();

        // GET: ShoppingCart
        public ActionResult Index()
        {
            var shoppingCart = (Dictionary<int, CartItemViewModel>)Session["cart"];

            if (shoppingCart == null)
            {
                shoppingCart = new Dictionary<int, CartItemViewModel>();
            }

            return View(shoppingCart);
        }

        public ActionResult AddToCart(int qty, int coffeeId)
        {
            Dictionary<int, CartItemViewModel> shoppingCart = null;

            if (Session["cart"] != null)
            {
                shoppingCart = (Dictionary<int, CartItemViewModel>)Session["cart"];
            }
            else
            {
                shoppingCart = new Dictionary<int, CartItemViewModel>();
            }

            Coffee coffee = db.Coffees.Find(coffeeId);

            CartItemViewModel item = new CartItemViewModel(qty, coffee);

            if (shoppingCart.ContainsKey(coffee.CoffeeID))
            {
                shoppingCart[coffee.CoffeeID].Qty += qty;
            }
            else
            {
                shoppingCart.Add(coffee.CoffeeID, item);
            }

            Session["cart"] = shoppingCart;

            return RedirectToAction("Index");
          
        } //end AddToCart

        public ActionResult RemoveFromCart(int id)
        {

            Dictionary<int, CartItemViewModel> shoppingCart = (Dictionary<int, CartItemViewModel>)Session["cart"];

            shoppingCart.Remove(id);

            Session["cart"] = shoppingCart;

            return RedirectToAction("Index");
        }

        public ActionResult UpdateCart(int coffeeId, int qty)
        {
            Dictionary<int, CartItemViewModel> shoppingCart = (Dictionary<int, CartItemViewModel>)Session["cart"];

            shoppingCart[coffeeId].Qty = qty;

            if (shoppingCart[coffeeId].Qty == 0)
            {
                shoppingCart.Remove(coffeeId);
            }

            Session["cart"] = shoppingCart;

            return RedirectToAction("Index");

        }
    }
}

StoreFront.UI.MVC/StoreFront.UI.MVC/Views/Filters/AjaxCreate0.cshtml
@model StoreFront.DATA.EF.Coffee


@* Step 19 - clean up html to display in single row, upate BeginForm() *@

@using (Html.BeginForm("AjaxCreate", "Filters", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    // id="CoffeeCreateForm"
    <div class="form-horizontal">
        @*<h4>Coffee</h4>
            <hr />*@
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CoffeeName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CoffeeName, new { htmlAttributes = new { @class = "form-control", placeholder = "Name" } })
                @Html.ValidationMessageFor(model => model.CoffeeName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypeID, "TypeID", htmlAttributes: new { @class = "control-label col-md-2", placeholder = "Type" })
            <div class="col-md-10">
                @Html.DropDownList("TypeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TypeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">

            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", placeholder = "Price" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">

            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", placeholder = "Description" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">

            <div class="checkbox">
                @Html.EditorFor(model => model.CoffeeStatusID)
                @*@Html.DropDownList("CoffeeStatusID", null, htmlAttributes: new { @class = "form-control" })*@
                @Html.ValidationMessageFor(model => model.CoffeeStatusID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">

            <div class="col-md-10">
                @Html.DropDownList("SupplierID", null, htmlAttributes: new { @class = "form-control", placeholder = "Supplier ID" })
                @Html.ValidationMessageFor(model => model.SupplierID, "", new { @class = "text-danger" })
            </div>
        </div>
        <!--TODO build out img upload utility-->
        @*<div class="form-group">
                @Html.LabelFor(model => model.Images, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Images, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Images, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">

            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control", placeholder = "Country" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">

            <div class="col-md-10">
                @Html.EditorFor(model => model.Region, new { htmlAttributes = new { @class = "form-control", placeholder = "Region" } })
                @Html.ValidationMessageFor(model => model.Region, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "CoffeeQS")
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StoreFront.UI.MVC/StoreFront.UI.MVC/Views/Filters/AjaxDelete.cshtml
@model StoreFront.DATA.EF.Coffee

@{
    ViewBag.Title = "AjaxDelete";
}


<div id="content-wrapper">
    <section id="about-us" class="white">
        <div class="container">
            <h2>AjaxDelete</h2>

            <h3>Are you sure you want to delete this?</h3>
            <div>
                <h4>Coffee</h4>
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.CoffeeName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.CoffeeName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Price)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Price)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Description)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Description)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Images)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Images)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Country)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Country)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Region)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Region)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.CoffeeStatu.StatusName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.CoffeeStatu.StatusName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.CoffeeSupplier.SupplierName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.CoffeeSupplier.SupplierName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.CoffeeType.Name)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.CoffeeType.Name)
                    </dd>

                </dl>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Delete" class="btn btn-default" /> |
                        @Html.ActionLink("Back to List", "CoffeeQS")
                    </div>
                }
            </div>
        </div>
    </section>
</div>

StoreFront.UI.MVC/StoreFront.UI.MVC/Views/Filters/AjaxEdit.cshtml
@model StoreFront.DATA.EF.Coffee

@using (Html.BeginForm("Edit", "Filters", FormMethod.Post, new { id = "CoffeeEditForm" }))
{
    @Html.AntiForgeryToken()

    <table>

        <tr>
            @Html.HiddenFor(model => model.CoffeeID)


            <td>
                @Html.EditorFor(model => model.CoffeeName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CoffeeName, "", new { @class = "text-danger" })
            </td>


            <td>
                @Html.DropDownList("TypeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TypeID, "", new { @class = "text-danger" })
            </td>



            <td>
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </td>



            <td>
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </td>



            <td>
                @Html.DropDownList("CoffeeStatusID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CoffeeStatusID, "", new { @class = "text-danger" })
            </td>


            <td>
                @Html.DropDownList("SupplierID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SupplierID, "", new { @class = "text-danger" })
            </td>



            <td>
                @Html.EditorFor(model => model.Images, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Images, "", new { @class = "text-danger" })
            </td>



            <td>
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </td>



            <td>
                @Html.EditorFor(model => model.Region, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Region, "", new { @class = "text-danger" })
            </td>


            <td>
                <input type="submit" value="Save" class="btn btn-default" />
            </td>

        </tr>
        <
    </table>
}

<div>
    @Html.ActionLink("Back to List", "CoffeeQS")
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StoreFront.UI.MVC/StoreFront.UI.MVC/Views/Filters/CoffeeQS.cshtml
@model IEnumerable<StoreFront.DATA.EF.Coffee>

@{
    ViewBag.Title = "Shop Coffee";
}

<div class="center">
    <img src="~/Content/images/coffeeBeans/Explore Our Offerings (1).jpg" alt="" style="width: 100%" class="header-image" />
</div>
<div>
    <section id="portfolio" class="white">
        <div class="container">
      
            <div id="content-wrapper" style="padding-top: 3%;">
                <div class="container">
                    <div id="content-wrapper">
                        <h2>Sustainable coffee choosen with purpose.</h2>
                        @if (User.IsInRole("Admin"))
                        {
                        <p>
                            @Html.ActionLink("Create", "AjaxCreate")
                            @*<a href="@Url.Action("AjaxCreate", "Filters")">Create</a>      *@
                        </p>
                        }
                        <table class="table data-table table--striped">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Images)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.CoffeeName)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Description)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Price)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Country)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Region)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.CoffeeType.Name)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.CoffeeSupplier.SupplierName)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.CoffeeStatu.StatusName)
                                    </th>


                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @*@Html.DisplayFor(modelItem => item.Images)*@
                                            <a href="@Url.Action("Details", "Coffee", new { id = item.Images})" title="@item.CoffeeName">
                                                <img src="~/Content/images/coffeemessenger/@item.Images" alt="@item.CoffeeName coffee image" style="max-height: 100px; width: auto;" />
                                            </a>
                                            <a href="@Url.Action("Details", "Coffee", new { id = item.CoffeeID} )"></a>
                                           
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.CoffeeName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Description)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Price)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Country)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Region)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.CoffeeType.Name)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.CoffeeSupplier.SupplierName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.CoffeeStatu.StatusName)
                                        </td>
                                        @if (User.IsInRole("Admin"))
                                        {
                                            <td>                                                
                                                <a href="@Url.Action("Edit", "Coffee", new { id=item.CoffeeID})">Edit</a> |
                                                <a href="@Url.Action("Delete", "Coffee", new { id = item.CoffeeID})">Delete</a>                                                
                                            </td>
                                        }
                                    </tr>
                                }
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>

            <div class="gap"></div>
        </div>
    </section>
</div>

@section scripts{
    <script>
        $(document).ready(function () {
            $('.data-table').DataTable({
                responsive: true
            });
        });
    </script>
}