StoreFront.UI.MVC/StoreFront.UI.MVC/Controllers/CoffeeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StoreFront.DATA.EF;
using StoreFront.UI.MVC.Utilities;

namespace StoreFront.UI.MVC.Controllers
{
    [Authorize]
    public class CoffeeController : Controller
    {
        private StoreFrontEntities db = new StoreFrontEntities();
        #region Scaffolded, Non-Ajax CRUD Functionality

        
        // GET: Coffee
        [AllowAnonymous]
        public ActionResult Index()
        {
            ViewBag.CoffeeStatusID = new SelectList(db.CoffeeStatus, "CoffeeStatusID", "StatusName");
            ViewBag.SupplierID = new SelectList(db.CoffeeSuppliers, "SupplierID", "SupplierName");
            ViewBag.TypeID = new SelectList(db.CoffeeTypes, "TypeID", "Name");
            var coffees = db.Coffees.Include(c => c.CoffeeStatu).Include(c => c.CoffeeSupplier).Include(c => c.CoffeeType);
            return View(coffees.ToList());
        }

        // GET: Coffee/Details/5 
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Coffee coffee = db.Coffees.Find(id);
            if (coffee == null)
            {
                return HttpNotFound();
            }
            return View(coffee);
        }

        // GET: Coffee/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.CoffeeStatusID = new SelectList(db.CoffeeStatus, "CoffeeStatusID", "StatusName");
            ViewBag.SupplierID = new SelectList(db.CoffeeSuppliers, "SupplierID", "SupplierName");
            ViewBag.TypeID = new SelectList(db.CoffeeTypes, "TypeID", "Name");
            return View();
        }

        // POST: Coffee/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]    
        public ActionResult Create([Bind(Include = "CoffeeID,CoffeeName,TypeID,Price,Description,CoffeeStatusID,SupplierID,Images,Country,Region")] Coffee coffee, HttpPostedFileBase coffeeBag)
        {
            if (ModelState.IsValid)
            {
                #region File Upload w/ Utility
                string file = "NoImage.png";

                if (coffeeBag != null)
                {
                    file = coffeeBag.FileName;

                    string ext = file.Substring(file.LastIndexOf("."));

                    string[] goodExts = {".jpeg",".jpg",".gif",".png" };

                    if (goodExts.Contains(ext))
                    {
                        file = Guid.NewGuid() + ext;

                        #region Resize Image

                        //file path
                        string savePath = Server.MapPath("~/Content/images/coffeemessenger");
                        //image file
                        Image convertedImage = Image.FromStream(coffeeBag.InputStream);
                        //max img size
                        int maxImageSize = 500;

                        //max thumb size
                        int maxThumbSize = 100;

                        //call the imageutlity to do work
                        ImageUtility.ResizeImage(savePath, file, convertedImage, maxImageSize, maxThumbSize);
                        #endregion
                    }
                    else
                    {
                        file = "NoImage.png";
                    }

                    coffee.Images = file;

                }
                #endregion
               // ViewBag.TypeID = new SelectList(db.CoffeeTypes, "TypeID", "Name");
                db.Coffees.Add(coffee);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CoffeeStatusID = new SelectList(db.CoffeeStatus, "CoffeeStatusID", "StatusName", coffee.CoffeeStatusID);
            ViewBag.SupplierID = new SelectList(db.CoffeeSuppliers, "SupplierID", "SupplierName", coffee.SupplierID);
            ViewBag.TypeID = new SelectList(db.CoffeeTypes, "TypeID", "Name", coffee.TypeID);
            return View(coffee);
        }

        // GET: Coffee/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Coffee coffee = db.Coffees.Find(id);
            if (coffee == null)
            {
                return HttpNotFound();
            }
            ViewBag.CoffeeStatusID = new SelectList(db.CoffeeStatus, "CoffeeStatusID", "StatusName", coffee.CoffeeStatusID);
            ViewBag.SupplierID = new SelectList(db.CoffeeSuppliers, "SupplierID", "SupplierName", coffee.SupplierID);
            ViewBag.TypeID = new SelectList(db.CoffeeTypes, "TypeID", "Name", coffee.TypeID);
            return View(coffee);
        }

        // POST: Coffee/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]      
        public ActionResult Edit([Bind(Include = "CoffeeID,CoffeeName,TypeID,Price,Description,CoffeeStatusID,SupplierID,Images,Country,Region")] Coffee coffee, HttpPostedFileBase coffeeBag)
        {
            if (ModelState.IsValid)
            {
                #region File Upload w/ Utility               

                string file = "";

                if (coffeeBag != null)
                {
                    
                    file = coffeeBag.FileName;                  

                    string ext = file.Substring(file.LastIndexOf("."));

                    string[] goodExts = { ".jpg", ".jpeg", ".png", ".gif" };

                    if (goodExts.Contains(ext))
                    {

                        
                        file = Guid.NewGuid() + ext;

                        #region Resize Image
                        
                        string savePath = Server.MapPath("~/Content/imgstore/books/");

                        Image convertedImage = Image.FromStream(coffeeBag.InputStream);

                        int maxImageSize = 500;

                        int maxThumbSize = 100;

                        ImageUtility.ResizeImage(savePath, file, convertedImage, maxImageSize, maxThumbSize);
                        #endregion

                        #region Delete the old image
                        if (coffee.Images != null && coffee.Images != "NoImage.png")
                        {
                            string path = Server.MapPath("~/Content/imgstore/books/");
                            ImageUtility.Delete(path, coffee.Images);
                        }
                        #endregion

                        coffee.Images = file;

                    }
                }
                #endregion
                db.Entry(coffee).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CoffeeStatusID = new SelectList(db.CoffeeStatus, "CoffeeStatusID", "StatusName", coffee.CoffeeStatusID);
            ViewBag.SupplierID = new SelectList(db.CoffeeSuppliers, "SupplierID", "SupplierName", coffee.SupplierID);
            ViewBag.TypeID = new SelectList(db.CoffeeTypes, "TypeID", "Name", coffee.TypeID);
            return View(coffee);
        }

        // GET: Coffee/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Coffee coffee = db.Coffees.Find(id);
            if (coffee == null)
            {
                return HttpNotFound();
            }
            return View(coffee);
        }

        // POST: Coffee/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]    
        public ActionResult DeleteConfirmed(int id)
        {
            Coffee coffee = db.Coffees.Find(id);
            db.Coffees.Remove(coffee);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        #endregion

        // step 2 

        // Step 9
        [AcceptVerbs(HttpVerbs.Post)]
        [Authorize(Roles = "Admin")]
        public JsonResult AjaxDelete(int id)
        {
            Coffee coffee = db.Coffees.Find(id);

            db.Coffees.Remove(coffee);
            db.SaveChanges();

            string confirmMessage = $"Delete Coffee item {coffee.CoffeeName} from the database!";

            return Json(new { id = id, message = confirmMessage });
        }

        //Step 13
        [HttpGet]
        public PartialViewResult CoffeeDetails(int id)
        {
            Coffee coffee = db.Coffees.Find(id);
            return PartialView(coffee);

            //Create partial View()
        }

        //[HttpGet]
        //[Authorize(Roles = "Admin")]
        //public JsonResult AjaxCreate()
        //{
        //    ViewBag.CoffeeStatusID = new SelectList(db.CoffeeStatus, "CoffeeStatusID", "StatusName");
        //    ViewBag.SupplierID = new SelectList(db.CoffeeSuppliers, "SupplierID", "SupplierName");
        //    ViewBag.TypeID = new SelectList(db.CoffeeTypes.OrderBy(c => c.Name), "TypeID", "Name");
        //    var coffee = db.Coffees.Include(c => c.CoffeeStatu).Include(c => c.CoffeeSupplier).Include(c => c.CoffeeType);
        //    return Json(coffee);
        //}


        //Create

StoreFront.UI.MVC/StoreFront.UI.MVC/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StoreFront.DATA.EF;

namespace StoreFront.UI.MVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CustomersController : Controller
    {
        private StoreFrontEntities db = new StoreFrontEntities();

        // GET: Customers
        public ActionResult Index()
        {
            return View(db.Customers.ToList());
        }

        // GET: Customers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // GET: Customers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CustomerID,FirstN,LastN,IsMember,Address,City,State,PostalCode,Phone,Email")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Customers.Add(customer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(customer);
        }

        // GET: Customers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CustomerID,FirstN,LastN,IsMember,Address,City,State,PostalCode,Phone,Email")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Customer customer = db.Customers.Find(id);
            db.Customers.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StoreFront.UI.MVC/StoreFront.UI.MVC/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StoreFront.DATA.EF;
using StoreFront.UI.MVC.Models;

namespace StoreFront.UI.MVC.Controllers
{
    public class ShoppingCartController : Controller
    {
        private StoreFrontEntities db = new StoreFrontEntities();

        // GET: ShoppingCart
        public ActionResult Index()
        {
            var shoppingCart = (Dictionary<int, CartItemViewModel>)Session["cart"];

            if (shoppingCart == null)
            {
                shoppingCart = new Dictionary<int, CartItemViewModel>();
            }

            return View(shoppingCart);
        }

        public ActionResult AddToCart(int qty, int coffeeId)
        {
            Dictionary<int, CartItemViewModel> shoppingCart = null;

            if (Session["cart"] != null)
            {
                shoppingCart = (Dictionary<int, CartItemViewModel>)Session["cart"];
            }
            else
            {
                shoppingCart = new Dictionary<int, CartItemViewModel>();
            }

            Coffee coffee = db.Coffees.Find(coffeeId);

            CartItemViewModel item = new CartItemViewModel(qty, coffee);

            if (shoppingCart.ContainsKey(coffee.CoffeeID))
            {
                shoppingCart[coffee.CoffeeID].Qty += qty;
            }
            else
            {
                shoppingCart.Add(coffee.CoffeeID, item);
            }

            Session["cart"] = shoppingCart;

            return RedirectToAction("Index");
          
        } //end AddToCart

        public ActionResult RemoveFromCart(int id)
        {

            Dictionary<int, CartItemViewModel> shoppingCart = (Dictionary<int, CartItemViewModel>)Session["cart"];

            shoppingCart.Remove(id);

            Session["cart"] = shoppingCart;

            return RedirectToAction("Index");
        }

        public ActionResult UpdateCart(int coffeeId, int qty)
        {
            Dictionary<int, CartItemViewModel> shoppingCart = (Dictionary<int, CartItemViewModel>)Session["cart"];

            shoppingCart[coffeeId].Qty = qty;

            if (shoppingCart[coffeeId].Qty == 0)
            {
                shoppingCart.Remove(coffeeId);
            }

            Session["cart"] = shoppingCart;

            return RedirectToAction("Index");

        }
    }
}

StoreFront.UI.MVC/StoreFront.UI.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewBag.Title | ANCHOR </title>
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/Content/css/pe-icons.css" rel="stylesheet">
    <link href="~/Content/css/prettyPhoto.css" rel="stylesheet">
    <link href="~/Content/css/animate.css" rel="stylesheet">
    <link href="~/Content/css/style.css" rel="stylesheet">
    @* Added *@
    <script src="https://kit.fontawesome.com/1f94d5f4f0.js" crossorigin="anonymous"></script>

    <!--Custom.css-->
    <link href="~/Content/css/custom.css" rel="stylesheet" />


    <script src="~/Scripts/js/jquery.js"></script>
    <link rel="shortcut icon" href="~/Content/images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="~/Content/images/ico/apple-touch-icon-144x144.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="~/Content/images/ico/apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="~/Content/images/ico/images/ico/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon-precomposed" href="~/Content/images/ico/apple-touch-icon-57x57.png">

    <!--jQuery DataTables-->
    <link href="//cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" />

    <link href="https://cdn.datatables.net/responsive/2.2.1/css/responsive.dataTables.min.css" rel="stylesheet" />

    @* AJAX Step 1 - Add <link> for jQuery UI in the <head> and add <scripts> for jQueryUI and jQuery AJAX at the bottom of the layout *@
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/south-street/jquery-ui.css">


</head><!--/head-->


<body>
    <div id="preloader"></div>
    <header class="navbar navbar-inverse navbar-fixed-top opaqued" role="banner">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index","Coffee")"><h1><span class="pe-7s-gleam bounce-in"></span>ANCHOR</h1></a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="@Url.Action("Index","Home")">Home</a></li>
                    <li><a href="@Url.Action("Index","Coffee")">Shop</a></li>
                    @*<li><a href="@Url.Action("Index","CoffeeSuppliers")">Our Partners</a></li>*@
                    <li><a href="@Url.Action("Contact","Home")">Contact</a></li>
                    <li><a href="@Url.Action("About","Home")">About</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account</a>
                        <div class="dropdown-menu account-dropdown">
                            @Html.Partial("_LoginPartial")
                        </div>
                    </li>
                    <li class="nav-item">
                        @{
                            Dictionary<int, StoreFront.UI.MVC.Models.CartItemViewModel> shoppingCart =
                                (Dictionary<int, StoreFront.UI.MVC.Models.CartItemViewModel>)Session["cart"];

                            int nbrItems = 0;

                            if (shoppingCart != null)
                            {
                                foreach (var item in shoppingCart)
                                {
                                    nbrItems += item.Value.Qty;
                                }
                            }

                        }
                        <a href="@Url.Action("Index", "ShoppingCart")">Cart<i class="fa fa-shopping-cart"></i><span class="cart-text">@nbrItems</span></a>
                    </li>
                </ul>
            </div>
        </div>
    </header><!--/header-->


    <div id="content-wrapper">

        @* Step 8 *@
        @*<div id="MessageDisplay" class="row">
            <div class="col-md-10 col-md-offset-1" id="MessageContent"></div>
        </div>*@
        @RenderBody()
    </div>


    <div id="footer-wrapper">
        <section id="bottom" class="">
            <div class="container">
                <div class="row">
                    <div class="col-md-3 col-sm-6 about-us-widget">
                        <h4>Ethically Sourced</h4>
                        <p> Our approach to sourcing is a part of the core philosophy of our company. Quality driven farmers cultivate their coffee crop to be its best. It is their work that builds the foundation for what makes great coffee. </p>
                    </div><!--/.col-md-3-->
                    <div class="col-md-3 col-sm-6">

                        <div>
                            <div class="media">
                                <div class="pull-left">
                                    <img class="widget-img" src="~/Content/images/coffeeBeans/nafinia-putra-Kwdp-0pok-I-unsplash.jpg" alt="">
                                </div>
                                <div class="media-body">
                                    <span class="media-heading"><a href="@Url.Action("Index","Coffee")">Shop Here</a></span>
                                    <small class="muted">Roasted to order, start your journey here.</small>
                                </div>
                            </div>
                            <div class="media">
                                <div class="pull-left">
                                    <img class="widget-img" src="~/Content/images/coffeeBeans/clint-mckoy-h28p96ICizo-unsplash.jpg" alt="">
                                </div>
                                <div class="media-body">
                                    <span class="media-heading"><a href="@Url.Action("About","Home")">Company History</a></span>
                                    <small class="muted">From humble beginnings </small>
                                </div>
                            </div>
                        </div>
                    </div><!--/.col-md-3-->
                    <div class="col-md-3 col-sm-6 float-end">
                        <address>
                            <strong>Anchor Coffee</strong><br>
                            4040 Southwest Boulevard Kansas City, Missouri, 86370<br>
                            @*<abbr title="Phone"><i class="fa fa-phone"></i></abbr>  +1-816-849-1286*@
                        </address>
                    </div> <!--/.col-md-3-->
                </div>
            </div>
        </section><!--/#bottom-->
        <div class="col-md-3 col-sm-6">
            <div>
                @if (User.IsInRole("Admin"))
                {
                    <a href="" class="dropdown-toggle" data-toggle="dropdown"> <b>Admin Tools:</b> </a>                   
                        <a href="@Url.Action("Index","Employees")">Employees</a>
                        <a href="@Url.Action("Index","Customers")">Customers</a>
                        <a href="@Url.Action("Index","CoffeeSuppliers")">Suppliers</a>                                       
                }
            </div>
        </div><!--/.col-md-3-->

        <footer id="footer" class="">
            <div class="container">
                <div class="row">
                    <div class="col-sm-8">
                        &copy; 2021 ANCHOR @*<a href="https://templatemag.com/bootstrap-templates/">Bootstrap templates</a>*@
                        @*<a id="gototop" class="gototop" href="@ViewBag.Title"><i class="fas fa-arrow-up"></i>Back To Top</a>*@<!--#gototop-->
                    </div>
                   
                </div>
            </div>
        </footer><!--/#footer-->
    </div>
    <script src="~/Scripts/js/bootstrap.min.js"></script>
    <script src="~/Scripts/js/jquery.prettyPhoto.js"></script>
    <script src="~/Scripts/js/plugins.js"></script>
    <script src="~/Scripts/js/init.js"></script>

    <!--JQuery DataTables-->
    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>*@
    <!-- Place scripts below jQuery (jQuery may already be referenced in your project) -->
    <script src="//cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.1/js/dataTables.responsive.min.js"></script>

    <!--ADDEDjQuery UI CDN-->
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <!-- ADDED jQuery Ajax CDN-->
    <script src="https://cdn.jsdelivr.net/jquery.ajax.unobtrusive/3.2.4/jquery.unobtrusive-ajax.min.js"></script>


    @RenderSection("scripts", required: false)
</body>
</html>

StoreFront.UI.MVC/StoreFront.UI.MVC/Views/Shared/_OriginalLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                    @if (Request.IsAuthenticated && User.IsInRole("Admin")) {
                        <li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin")</li>
                        <li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>